# Generated by Django 3.0.3 on 2020-03-07 03:39

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200301_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='geom_line',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='feature',
            name='geom_poly',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
