# Generated by Django 3.0.3 on 2020-03-18 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200309_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='type',
            new_name='placetype',
        ),
    ]
