# Generated by Django 3.0.3 on 2020-04-15 21:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200318_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='bounds',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=8, max_digits=11), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='maxzoom',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='minzoom',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
