# Generated by Django 3.0.3 on 2020-06-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='flag',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
