# Generated by Django 3.0.3 on 2020-06-08 16:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_name_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='year',
            new_name='year_pub',
        ),
        migrations.AddField(
            model_name='map',
            name='when',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='when_constant',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='label',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
