# Generated by Django 3.0.3 on 2020-06-09 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200608_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aat_id', models.IntegerField(unique=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('term', models.CharField(max_length=100)),
                ('term_full', models.CharField(max_length=100)),
                ('note', models.TextField(max_length=3000)),
                ('fclass', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'placetypes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProjectPlacetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placetype', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='main.Placetype')),
                ('project', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='main.Project')),
            ],
            options={
                'db_table': 'project_placetype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MapPlacetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='main.Map')),
                ('placetype', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='main.Placetype')),
            ],
            options={
                'db_table': 'map_placetype',
                'managed': True,
            },
        ),
    ]
