# Generated by Django 3.0.3 on 2020-06-11 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_mapplacetype_placetype_projectplacetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectplacetype',
            name='source_label',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectplacetype',
            name='placetype',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='main.Placetype', to_field='aat_id'),
        ),
    ]
