# Generated by Django 3.0.3 on 2020-06-11 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200611_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectplacetype',
            old_name='placetype',
            new_name='aattype',
        ),
    ]
